<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.13">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="David Nierman">
<meta name="dcterms.date" content="2026-05-18">
<meta name="description" content="Fitting a Poisson regression model via maximum likelihood to estimate the effect of Blueprinty’s software on patent awards.">

<title>Poisson Regression and Maximum Likelihood Estimation – David Nierman</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-ac077c1e730dfeb5e42400639d17284e.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-6b71721d8aceb696804222920b4299b1.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed fullcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">David Nierman</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../resume.html"> 
<span class="menu-text">Resume</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../projects.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Poisson Regression and Maximum Likelihood Estimation</h1>
<p class="subtitle lead">A Case Study of Blueprinty’s Software and Patent Awards</p>
</div>

<div>
  <div class="description">
    Fitting a Poisson regression model via maximum likelihood to estimate the effect of Blueprinty’s software on patent awards.
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>David Nierman </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 18, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>Blueprinty is a small software company that develops tools specifically designed to help firms prepare and submit patent applications to the US Patent Office. Their marketing team wants to make the case that engineering firms using Blueprinty’s software have a higher rate of patent approval than those that do not.</p>
<p>Ideally, evaluating this claim would require panel data tracking each firm’s patent success rate both before and after adopting the software — a clean before-and-after comparison that would isolate the software’s effect. No such longitudinal data exists. Instead, Blueprinty has assembled a cross-sectional dataset of 1,500 mature (non-startup) engineering firms, capturing each firm’s number of patents awarded over the last five years, its regional location, its age since incorporation, and whether or not it is a Blueprinty customer.</p>
<p>The core difficulty is that Blueprinty’s customers are not randomly assigned. Firms that choose to adopt the software may differ systematically from those that do not — perhaps they are older, more established, or concentrated in regions with historically higher patent activity. Any raw difference in patent counts between customers and non-customers could therefore reflect those underlying firm characteristics rather than a genuine effect of the software. Untangling the software’s contribution from these pre-existing differences is the central analytical challenge of this study.</p>
</section>
<section id="exploring-the-data" class="level2">
<h2 class="anchored" data-anchor-id="exploring-the-data">Exploring the Data</h2>
<div id="5246adf4" class="cell" data-execution_count="1">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw3_questions_files/figure-html/cell-2-output-1.png" width="950" height="381" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Blueprinty customers average 4.13 patents over the last five years, compared to 3.47 for non-customers — a meaningful gap on its face. Both distributions are right-skewed, with most firms clustered at low patent counts and a long tail of high-output firms. The customer distribution appears shifted rightward, suggesting customers tend to receive more patents. However, because customers are not randomly assigned, this difference may reflect underlying firm characteristics — such as age or region — rather than any effect of the software itself.</p>
<div id="99095bae" class="cell" data-execution_count="2">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw3_questions_files/figure-html/cell-3-output-1.png" width="758" height="374" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The Northeast stands out sharply: customers make up a majority of firms in that region, while all other regions are dominated by non-customers. This regional concentration matters because if Northeast firms also tend to win more patents for reasons unrelated to Blueprinty — stronger engineering ecosystems, proximity to patent attorneys, etc. — then the raw customer advantage in patent counts could be partly a Northeast effect rather than a software effect.</p>
<div id="fba1126c" class="cell" data-execution_count="3">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw3_questions_files/figure-html/cell-4-output-1.png" width="949" height="381" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The age distributions of customers and non-customers are broadly similar — both centered in the mid-twenties — but customers skew slightly older on average (26.9 years vs.&nbsp;26.1 years for non-customers). Older firms have had more time to develop patent portfolios and internal processes for filing applications, so even a modest age difference could inflate the apparent patent advantage among customers. Taken together, the regional and age imbalances underscore why a simple comparison of means is insufficient: any rigorous assessment must control for these confounders.</p>
</section>
<section id="a-simple-poisson-model-via-maximum-likelihood" class="level2">
<h2 class="anchored" data-anchor-id="a-simple-poisson-model-via-maximum-likelihood">A Simple Poisson Model via Maximum Likelihood</h2>
<p>The number of patents awarded to each firm is a count — a non-negative integer. This rules out the Normal distribution as a natural generative model: a Normal can assign positive probability to negative or fractional values, neither of which makes sense for patent counts. The Poisson distribution is the standard starting point for non-negative integer outcomes. It is parameterized by a single rate <span class="math inline">\(\lambda &gt; 0\)</span>, which represents the expected number of events, and it assigns probability only to the non-negative integers <span class="math inline">\(\{0, 1, 2, \ldots\}\)</span>. We therefore model each firm’s patent count <span class="math inline">\(Y_i\)</span> as an independent draw from a Poisson distribution with rate <span class="math inline">\(\lambda\)</span>.</p>
<p>Given <span class="math inline">\(n\)</span> independent observations <span class="math inline">\(Y_1, Y_2, \ldots, Y_n\)</span> each drawn from a Poisson distribution with rate <span class="math inline">\(\lambda\)</span>, the probability mass function for a single observation is:</p>
<p><span class="math display">\[
f(Y_i \mid \lambda) = \frac{e^{-\lambda}\lambda^{Y_i}}{Y_i!}
\]</span></p>
<p>Because the observations are independent, the joint likelihood is the product of the individual probabilities:</p>
<p><span class="math display">\[
L(\lambda \mid \mathbf{Y}) = \prod_{i=1}^{n} \frac{e^{-\lambda}\lambda^{Y_i}}{Y_i!}
\]</span></p>
<p>Taking the natural log converts the product into a sum, which is much easier to work with analytically:</p>
<p><span class="math display">\[
\ell(\lambda \mid \mathbf{Y}) = \log L(\lambda \mid \mathbf{Y}) = \sum_{i=1}^{n} \left[ -\lambda + Y_i \log \lambda - \log(Y_i!) \right]
\]</span></p>
<p>Pulling out the terms that do not depend on the index <span class="math inline">\(i\)</span>:</p>
<p><span class="math display">\[
\ell(\lambda \mid \mathbf{Y}) = -n\lambda + \log(\lambda)\sum_{i=1}^{n} Y_i - \sum_{i=1}^{n} \log(Y_i!)
\]</span></p>
<p>The last term is a constant with respect to <span class="math inline">\(\lambda\)</span> and plays no role in maximization. The MLE is found by differentiating and setting the derivative to zero, which yields <span class="math inline">\(\hat{\lambda} = \bar{Y}\)</span> — the sample mean.</p>
<div id="292ef243" class="cell" data-execution_count="4">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw3_questions_files/figure-html/cell-5-output-1.png" width="758" height="374" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The curve rises steeply from low values of <span class="math inline">\(\lambda\)</span>, reaches a single peak, then falls off gradually to the right. The peak — marked by the red dashed line at <span class="math inline">\(\hat{\lambda} \approx\)</span> 3.69 — is the maximum likelihood estimate: the value of <span class="math inline">\(\lambda\)</span> that makes the observed patent counts most probable under the Poisson model. Reading the MLE off the plot is straightforward: it is simply the <span class="math inline">\(\lambda\)</span> value directly below the highest point on the curve.</p>
<section id="analytical-mle" class="level3">
<h3 class="anchored" data-anchor-id="analytical-mle">Analytical MLE</h3>
<p>To find the MLE analytically, we differentiate the log-likelihood with respect to <span class="math inline">\(\lambda\)</span> and set the result equal to zero. Starting from:</p>
<p><span class="math display">\[
\ell(\lambda \mid \mathbf{Y}) = -n\lambda + \log(\lambda)\sum_{i=1}^{n} Y_i - \sum_{i=1}^{n} \log(Y_i!)
\]</span></p>
<p>Taking the derivative:</p>
<p><span class="math display">\[
\frac{d\ell}{d\lambda} = -n + \frac{1}{\lambda}\sum_{i=1}^{n} Y_i
\]</span></p>
<p>Setting this equal to zero and solving:</p>
<p><span class="math display">\[
\hat{\lambda}_{\text{MLE}} = \frac{1}{n}\sum_{i=1}^{n} Y_i = \bar{Y}
\]</span></p>
<p>The MLE is simply the sample mean — a reassuring result, since <span class="math inline">\(\lambda\)</span> is the mean of the Poisson distribution by definition.</p>
</section>
<section id="numerical-mle" class="level3">
<h3 class="anchored" data-anchor-id="numerical-mle">Numerical MLE</h3>
<div id="5a395f93" class="cell" data-execution_count="5">
<div class="cell-output cell-output-display">
<table class="dataframe table table-sm caption-top table-striped small">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">Method</th>
<th data-quarto-table-cell-role="th">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Numerical MLE</td>
<td>3.6847</td>
</tr>
<tr class="even">
<td>Sample mean</td>
<td>3.6847</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The numerical optimizer arrives at essentially the same answer as the sample mean (3.6847 vs.&nbsp;3.6847), confirming the analytical result. This agreement is expected: both approaches are solving the same problem — one algebraically, one computationally — so they must converge to the same value.</p>
</section>
</section>
<section id="poisson-regression" class="level2">
<h2 class="anchored" data-anchor-id="poisson-regression">Poisson Regression</h2>
<p>The simple Poisson model assumed every firm shares the same rate <span class="math inline">\(\lambda\)</span>. That is too restrictive: older firms, Northeast firms, and Blueprinty customers all plausibly have different expected patent counts. Poisson regression relaxes this by letting each firm have its own rate <span class="math inline">\(\lambda_i\)</span> that depends on its observed characteristics:</p>
<p><span class="math display">\[
Y_i \sim \text{Poisson}(\lambda_i) \qquad \text{where} \qquad \lambda_i = \exp(X_i'\beta)
\]</span></p>
<p>Here <span class="math inline">\(X_i\)</span> is a vector of covariates for firm <span class="math inline">\(i\)</span> (age, region indicators, customer status) and <span class="math inline">\(\beta\)</span> is a vector of coefficients to be estimated. The exponential function serves as the link between the linear predictor <span class="math inline">\(X_i'\beta\)</span> — which can take any real value — and the rate parameter <span class="math inline">\(\lambda_i\)</span>, which must be strictly positive. By exponentiating, we guarantee <span class="math inline">\(\lambda_i &gt; 0\)</span> for any value of <span class="math inline">\(\beta\)</span>, making the model well-defined for count outcomes.</p>
<p>The log-likelihood function is updated to accept a covariate matrix <span class="math inline">\(X\)</span> and coefficient vector <span class="math inline">\(\beta\)</span>, computing firm-specific rates via <span class="math inline">\(\lambda_i = \exp(X_i'\beta)\)</span>:</p>
<p>The design matrix includes an intercept, firm age, age squared, region dummies (Midwest dropped as the reference category), and the customer indicator. Age squared is included because the relationship between firm age and patenting is unlikely to be linear — very young and very old firms may patent at different rates than a straight line would predict. One region must be omitted to avoid perfect collinearity: if we included all five region dummies, their sum would equal the intercept column, making <span class="math inline">\(X\)</span> rank-deficient and the coefficients non-identifiable.</p>
<div id="29dcf604" class="cell" data-execution_count="7">
<div class="cell-output cell-output-display">
<b>Poisson Regression MLE — Coefficients and Standard Errors</b><br>
<table class="dataframe table table-sm caption-top table-striped small">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Coefficient</th>
<th data-quarto-table-cell-role="th">Std. Error</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">intercept</th>
<td>-0.50985</td>
<td>0.18321</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">age</th>
<td>0.14869</td>
<td>0.01387</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">age2</th>
<td>-0.00297</td>
<td>0.00026</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Northeast</th>
<td>0.02916</td>
<td>0.04363</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Northwest</th>
<td>-0.01758</td>
<td>0.05378</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">South</th>
<td>0.05655</td>
<td>0.05266</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Southwest</th>
<td>0.05057</td>
<td>0.04720</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">iscustomer</th>
<td>0.20761</td>
<td>0.03090</td>
</tr>
</tbody>
</table>
</div>
</div>
<section id="glm-check" class="level3">
<h3 class="anchored" data-anchor-id="glm-check">GLM Check</h3>
<div id="0d86a4aa" class="cell" data-execution_count="8">
<div class="cell-output cell-output-display">
<b>Comparison: Manual MLE vs. statsmodels GLM</b><br>
<table class="dataframe table table-sm caption-top table-striped small">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">MLE Coef</th>
<th data-quarto-table-cell-role="th">MLE SE</th>
<th data-quarto-table-cell-role="th">GLM Coef</th>
<th data-quarto-table-cell-role="th">GLM SE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">intercept</th>
<td>-0.50985</td>
<td>0.18321</td>
<td>-0.50892</td>
<td>0.18318</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">age</th>
<td>0.14869</td>
<td>0.01387</td>
<td>0.14862</td>
<td>0.01387</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">age2</th>
<td>-0.00297</td>
<td>0.00026</td>
<td>-0.00297</td>
<td>0.00026</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Northeast</th>
<td>0.02916</td>
<td>0.04363</td>
<td>0.02917</td>
<td>0.04363</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Northwest</th>
<td>-0.01758</td>
<td>0.05378</td>
<td>-0.01757</td>
<td>0.05378</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">South</th>
<td>0.05655</td>
<td>0.05266</td>
<td>0.05656</td>
<td>0.05266</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Southwest</th>
<td>0.05057</td>
<td>0.04720</td>
<td>0.05058</td>
<td>0.04720</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">iscustomer</th>
<td>0.20761</td>
<td>0.03090</td>
<td>0.20759</td>
<td>0.03090</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The coefficient estimates from both approaches are identical. The standard errors also match closely here because the numerical Hessian is computed via a fine-grained finite-difference approximation; in general, slight discrepancies can arise because <code>sm.GLM</code> uses the analytic (expected) information matrix while numerical optimizers approximate it, but with well-behaved data and a tight grid the two converge.</p>
</section>
<section id="interpretation" class="level3">
<h3 class="anchored" data-anchor-id="interpretation">Interpretation</h3>
<p>The age coefficient is positive (≈ 0.149) and the age-squared coefficient is negative (≈ −0.003), together describing a concave inverted-U relationship: patent output rises with firm maturity but at a decreasing rate and eventually plateaus. The region dummies are all small and statistically modest relative to their standard errors, suggesting that after controlling for age and customer status, regional differences in patent rates are limited.</p>
<p>The customer coefficient is 0.208 (SE ≈ 0.031), which is highly significant. Exponentiating gives <span class="math inline">\(e^{0.208} \approx 1.23\)</span>, meaning Blueprinty customers are estimated to receive about <strong>23% more patents</strong> than otherwise identical non-customer firms. The sign is in the direction the marketing team hoped for, and the magnitude is economically meaningful. That said, this is still an observational estimate — unobserved firm-level differences not captured by age and region could still confound the result.</p>
</section>
</section>
<section id="the-effect-of-blueprintys-software" class="level2">
<h2 class="anchored" data-anchor-id="the-effect-of-blueprintys-software">The Effect of Blueprinty’s Software</h2>
<p>Because Poisson regression is multiplicative in <span class="math inline">\(\lambda\)</span>, the customer coefficient (≈ 0.208) does not translate directly into “additional patents.” To produce a more interpretable estimate we use the counterfactual prediction approach: take the observed covariate matrix and flip every firm’s customer status to 0, then to 1, and compare predicted patent counts.</p>
<div id="6fcfca02" class="cell" data-execution_count="9">
<div class="cell-output cell-output-display">
<b>Counterfactual Prediction Results</b><br>
<table class="dataframe table table-sm caption-top table-striped small">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">Scenario</th>
<th data-quarto-table-cell-role="th">Avg. Predicted Patents</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>All firms as non-customers</td>
<td>3.436</td>
</tr>
<tr class="even">
<td>All firms as customers</td>
<td>4.229</td>
</tr>
<tr class="odd">
<td>Average treatment effect</td>
<td>0.793</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Holding each firm’s age and region fixed at its observed values, switching customer status from 0 to 1 increases predicted patents by an average of 0.79 over five years — roughly <strong>0.79 additional patents per firm</strong>. Put differently, the model estimates that Blueprinty’s software is associated with about one extra patent every six years for a typical firm in this sample.</p>
<p>This finding is consistent with Blueprinty’s marketing claim, but it does not establish causality. The analysis controls for age and region, yet several potentially important confounders remain unaddressed:</p>
<ul>
<li><strong>Internal R&amp;D investment</strong> — firms that spend heavily on research are both more likely to patent and more likely to invest in specialized tools like Blueprinty’s software. Higher patent output may reflect R&amp;D intensity rather than the software itself.</li>
<li><strong>Patent attorney quality</strong> — firms with access to experienced IP counsel tend to file more successful applications. Such firms may also be more likely to adopt purpose-built patent software.</li>
<li><strong>Firm size and revenue</strong> — larger firms have more resources to buy software subscriptions and more engineers generating patentable ideas. Size is not in the dataset, so its effect is absorbed into the error term.</li>
<li><strong>Prior patent experience</strong> — firms already skilled at navigating the patent process may adopt Blueprinty to manage growing workloads, rather than using it to improve their odds. Selection based on prior success would inflate the apparent customer effect.</li>
</ul>
<p>Without a randomized assignment of software access — or a credible natural experiment — we cannot rule out that these unobserved differences, rather than the software, explain the gap in patent counts.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>